web:
  upload-path: E:/img
spring:
  freemarker:
    charset: UTF-8
    request-context-attribute: request
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
    #监控统计拦截的filters
    filters: stat
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性
    url: jdbc:mysql://127.0.0.1:3306/sharedlibrary?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: root
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-betwelis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  mvc:
    static-path-pattern: /**
  data:
    elasticsearch:
      cluster-name: myes
      cluster-nodes: 127.0.0.1:9300
#设置tomcat端口
server:
  port: 8080
#生成实体别名
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.share.pojo
logging:
  level:
    com:
     share:
       blogs:
         mapper: debug
       invitation:
         mapper: debug
       users:
         mapper: debug
       forum:
         mapper: debug
#  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #field-strategy: 2
    #驼峰下划线转换
    #db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false